language: python
sudo: false
python: 2.7
env:
  matrix:
    - TOXENV=py26-django14
    - TOXENV=py26-django15
    - TOXENV=py26-django16
    - TOXENV=py27-django14
    - TOXENV=py27-django15
    - TOXENV=py27-django16
    - TOXENV=py27-django17

install:
  - pip install tox
script: tox
