language: python
sudo: false
matrix:
  include:
    - python: '2.7'
      env: TOXENV=py27-django18
    - python: '2.7'
      env: TOXENV=py27-django110
    - python: '2.7'
      env: TOXENV=py27-django111
    - python: '3.6'
      env: TOXENV=py36-django18
    - python: '3.6'
      env: TOXENV=py36-django110
    - python: '3.6'
      env: TOXENV=py36-django111
install:
  - pip install tox
script: tox

