language: python
sudo: false
matrix:
  include:
    - python: '3.6'
      env: TOXENV=py36-django111
    - python: '3.6'
      env: TOXENV=py36-django22
    - python: '3.7'
      env: TOXENV=py37-django22
install:
  - pip install tox
script: tox

